default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: AIapp_development
  host: localhost
  username: postgres
  password: admin123

test:
  <<: *default
  database: AIapp_test
  host: localhost
  username: postgres
  password: admin123

production:
  <<: *default
  database: AIapp_production
