default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: AIapp_development
  host: <%= ENV['POSTGRES_HOST %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_DBUSER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: AIapp_test
  host: <%= ENV['POSTGRES_HOST %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_DBUSER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: AIapp_production
  url: <%= ENV[DATABASE_URL] %>
  # username: AIapp
  # password: <%= ENV["AIAPP_DATABASE_PASSWORD"] %>
  # username: <%= ENV['POSTGRES_DBUSER'] %>
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
